version: "3"

services:
    nginx:
        image: nginx
        container_name: ${CONTAINER_NAME}
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./${CONFIG_FILE}:/etc/nginx/nginx.conf
            - ./certs:/etc/nginx/certs
        networks:
            default:
                ipv4_address: 172.1.0.10

networks:
  default:
    external: true
    name: main-network 
