version: "3"

services:
    nginx:
        image: nginx
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./certs:/etc/nginx/certs
        depends_on:
            - server
            - server-2
        networks:
            default:
                ipv4_address: 172.1.0.10

networks:
  default:
    external: true
    name: main-network 
